import api from './api';

// Helper function to generate a valid MongoDB ObjectId
// MongoDB ObjectIds are 24-character hex strings
export const generateObjectId = (): string => {
  const timestamp = Math.floor(new Date().getTime() / 1000).toString(16).padStart(8, '0');
  const machineId = Math.floor(Math.random() * 16777216).toString(16).padStart(6, '0');
  const processId = Math.floor(Math.random() * 65536).toString(16).padStart(4, '0');
  const counter = Math.floor(Math.random() * 16777216).toString(16).padStart(6, '0');
  return timestamp + machineId + processId + counter;
};

interface Answer {
  index: number;
  questionId?: string; // MongoDB ObjectId - optional, will be generated by MongoDB
  originalQuestionId: string; // Our manual ID (q1, q2, etc.)
  question: string;
  type: string;
  answer: string;
}

interface SectionAnswers {
  sectionId?: string; // MongoDB ObjectId - optional, will be generated by MongoDB
  originalSectionId: string; // Our manual section ID (101A, 101B, etc.)
  isCompleted: boolean;
  answers: Answer[];
}

interface UserInputData {
  _id?: string; // MongoDB ObjectId for the document
  userId: string; // MongoDB ObjectId
  categoryId: string; // MongoDB ObjectId - required by backend
  originalCategoryId: string; // Our manual category ID (1, 2, etc.)
  subCategoryId: string; // MongoDB ObjectId - required by backend
  originalSubCategoryId: string; // Our manual subcategory ID (101, 102, etc.)
  answersBySection: SectionAnswers[];
}

const userInputService = {
  // Create a new user input
  createUserInput: async (data: UserInputData) => {
    const response = await api.post('/user-inputs', data);
    return response.data;
  },

  // Get user input by ID
  getUserInput: async (id: string) => {
    const response = await api.get(`/user-inputs/${id}`);
    return response.data;
  },

  // Get user inputs by user ID and category ID
  getUserInputsByUserAndCategory: async (userId: string, categoryId: string) => {
    const response = await api.get('/user-inputs', {
      params: { userId, categoryId }
    });
    return response.data;
  },

  // Get user inputs for a specific subcategory
  getUserInputsBySubcategory: async (userId: string, originalCategoryId: string, originalSubCategoryId: string) => {
    const response = await userInputService.getUserInputsByUserAndCategory(userId, originalCategoryId);

    // Ensure we have an array to work with
    const allUserInputs = Array.isArray(response) ? response : [];

    // Filter for the specific subcategory
    return allUserInputs.filter((input: UserInputData) =>
      input.originalSubCategoryId === originalSubCategoryId
    );
  },

  // Update user input
  updateUserInput: async (id: string, data: Partial<UserInputData>) => {
    const response = await api.patch(`/user-inputs/${id}`, data);
    return response.data;
  }
};

// Helper function to convert user input data to form values
export const convertUserInputToFormValues = (userInput: UserInputData): Record<string, string> => {
  if (!userInput || !userInput.answersBySection) {
    return {};
  }

  const formValues: Record<string, string> = {};

  // Process all sections and their answers
  userInput.answersBySection.forEach((section: SectionAnswers) => {
    section.answers.forEach((answer: Answer) => {
      if (answer.originalQuestionId && answer.answer) {
        formValues[answer.originalQuestionId] = answer.answer;
      }
    });
  });

  return formValues;
};

export default userInputService;
